### ISSUE TITLE
Paging for "open bounties" and activity views

### ISSUE THREAD

**Issue by tpatja** [status-im/open-bounty#156]
Currently, if there is a lot of data in the system, the views get very long vertically.

Implement client-side paging to UI on "open bounties" and activity views.

**Comment by tpatja** [comment]
UI mockups needed.

**Comment by denis-sharypin** [comment]
@tpatja  There is a mockup already of it https://zpl.io/V1yKxeB
Does it help?

**Comment by tpatja** [comment]
Thanks @denis-sharypin, this mockup should be enough

**Comment by churik** [comment]
Have several comments according pagination feature:
1) On hover page number or on buttons "Back"/ "Next" mouse cursor has `auto` CSS property instead of `pointer`
2) On Safari and FF clicking on page number redirects to random place on page.
Video: https://drive.google.com/open?id=1ZAHPgvmb1C7tuQmYR9-kx_hPVyHRjDc4
3) would be nice to mark as disabled button "Back"\"Next" when they are not available (page is first or last)
![pagin](https://user-images.githubusercontent.com/4557972/35211670-24f1a398-ff60-11e7-8f8a-6e9c219c2ef6.png)

**Comment by churik** [comment]
@pablodip thanks a lot!

**Comment by churik** [comment]
Checked on https://openbounty.status.im:444/ - Chrome 64.0, Safari 11.0.1, FF 57.0.
For mobile: Iphone 7, Safari.
