### ISSUE TITLE
Script to create a private Ethereum network for dev and test environments

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#223]
### Description

Isolated dev and test environments help create better software, since those isolated environments are not polluted with external states (they are deterministic) and they are normally very fast, and local.

Current dev and test environments of the SOB depend on the public test network, which make the environments not being deterministic, nor fast (it takes a good time to set up), nor local.

I think this could be solved by having a script in the repo to create a private Ethereum network so that network can be used most of the times when developing and when running tests.

### User Stories

As a developer/CI server I want to have a script to run to create a private Ethereum network, so that I can have an isolated, deterministic, fast and local environment.

### Expected Behaviour

Have a script in the repo, probably in the `scripts` directory, that I can run and create a private Ethereum network.

### Actual Behaviour

Work with the public test Ethereum network.

### Some notes

* The script should allow to create several networks if called in parallel with different parameters.
* The script should create a network with a few accounts that have some ethers.
* The network should have the contracts used by the SOB.
* The network should have a few tokens deployed so that the SOB can use them.
* The network should be created in a deterministic way if possible, that is, providing always an equal network, with the same accounts, and the same contracts, and the same addresses.
* The network should be done with [Ganache](https://github.com/trufflesuite/ganache) or something similar that helps debugging.

**Comment by 3esmit** [comment]
I agree to have the deploy of contracts automated, user just need run the RPC node willing to deploy them, but the script that would run it is Truffle (and possibly Ganashe) 

As @jeluard mentioned, Ganache is an out-of-the-box solution, that works with truffle. Truffle is an awesome development framework, it contains testcases and deploy (migration) scripts.

As we are using a "contract library" (mastercopy) with forwarders created by a factory contract, the probable path to follow is implement a migrations to deploy the "contract library" (mastercopy) and the factory.
Some changes would be needed in the contract to make this auto-deploy possible, because the current contract being used have the "contract library" (mastercopy) hardcoded in a Stub contract that is deployed by a factory. You can read this in line 222 of factory contract. https://etherscan.io/address/0x3b9a3c062bdb640b5039c0ccda4157737d732f95#code

I was working in changes that would make this auto deploy possible, it can be found here https://github.com/status-im/open-bounty/tree/a3931724123edb938d6fc7dd7fd42cace5f3ece8/contracts
This was reverted because of an incompatibility with newer versions of solidity and web3j used by SOB-bot to understand ABI and other ethereum stuff. 
A newer version of solidity is required for the improvements in gas at deploy by using new post-byzantium opcodes `returndatasize` and `returndatacopy` that allow contracts to return arrays. 
**Supporting truffle migration can be done with older solidity by replacing the hardcoded address from contract by an address set only in constructor.**  
@tpatja, do you have news on this incompatibility?

**Comment by arash009** [comment]
How do we solve this incompatibility? Do we need to upgrade the version of solidity?
What are the next steps?

**Comment by pablodip** [comment]
@arash009 That Ricardo's response is a little outdated with all that we talked in that conversation. The conclusion was that we can do it (that incompatibility isn't a block for this issue), and that we need to deploy some things apart from the SOB contracts, things that are normally already deployed and shared in public networks, like the token registry and some test tokens, including the Status one.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x36430abaa036576a359f47759648ddfa1f3b2b933acc69e64a235400b5a23b61](https://etherscan.io/tx/0x36430abaa036576a359f47759648ddfa1f3b2b933acc69e64a235400b5a23b61)

**Comment by kdeme** [comment]
Is this still needed? If so, can give it a go.
