### ISSUE TITLE
Autobounty Position

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#272]
It isn't clear (at least to me) the position of the Autobounty in the SOB. So let's try to define it. :) (Or just let me know where it is defined if it is already defined. :)

1.) As I understand the Autobounty is just an external addon for the SOB, at least now, but not a SOB core feature. Is that right?
2.) @churik  said that she would like to add it to the SOB. How exactly and what for? If it isn't a core feature that the SOB offers right now, not sure if we need that.
3.) How does the Autobounty depend on the SOB? That is, is it a problem if things change in the SOB that can affect the Autobounty? As far as I understand it just depends on the smart contracts on the SOB, so just if those smart contracts change it affects the Autobounty.
4.) Who is responsible for maintaining and running the Autobounty? To what I know @andytudhope  is the one that has been working on it.
5.) Are there any plans to make the Autobounty a core feature? In that case, I guess it would need to be done in Clojure wouldn't it?

**Comment by churik** [comment]
2), 4), 5) afaik Autobounty will supposed to be a core feature and @andytudhope wants to use it with all future bounty issues, but initially it was requested by Aragon team.
I'm not sure who will care about autobounty bot maintanence (SOB team or external contributor or Aragon team)
May be I'm wrong, because a source of all info is only my point of view from slack channel conversations.

cc @andytudhope 
cc @arash009

**Comment by andytudhope** [comment]
Defining it here for some further formailisation is fine by me.

1. Yes.
2. Will answer below, and it also affects 3.
4. I am.
5. Agree.

So, the idea for this was to find someone capable of converting the little nod.js script written by the Aragon team into a bot that was ready for production and could be used by early adopters like Aragon and Riot. We then plan to see if it is a useful and safe add-on feature for these orgs.

If it is, and all works as expected, the plan is to put up another bounty to convert this all into Clojure so that it can be included as a core feature of the panned admin dashboard - i.e. org admins could simply identify bounty issues, specify a size and have the SOB frontend deploy and fund them all in one go.

3. As it currently stands, Autobounty does NOT depend on anything in SOB at all, even the contracts. What it requires is that the org add another GH app to their repos that simply listens for comments from the SOB bot, looks at the address, looks at the bounty size label and funds the appropriate bounty contract address with the right amount of funds.

Ultimately, as I have been thinking about this, having it as a core feature on the admin dashboard is really prize #1, because that means we can simply have org admins `allow` SOB to spend a certain amount of funds on their behalf each week/month and we could achieve the same "autofunding" effect without needing to put private keys anywhere close to where they can be found (as is currently the case with this autobounty bot).

**Comment by pablodip** [comment]
@andytudhope Thank you for all that info! :)

I think that it is better to keep it as a separated entity and integrate it here in the SOB when we have already tested it and want it to become a core feature. What do you think?

Btw, when we want it to become a core feature, it could well be a swarm idea. :)
