### ISSUE TITLE
GitHub interface: replace repo_name with repo_id

### ISSUE THREAD

**Issue by siphiuel** [status-im/open-bounty#292]
*Type*: Bug

### Description
When a GitHub repo is renamed, no notification is delivered via OpenBounty GitHub App webhook. So an old repo name is being stored in the database, which is not good, as it is used for some aspects of the functionality, like QR code generation, repo fetching from DB, etc.

### Solution
Replace all usage of `repo_name` in code when it is used as a repo identifier with references to `repo_id`, which is immutable. Perhaps it makes sense to check `repo_name` field in each GH webhook delivery and update the DB value if changed, so that the UI reflects name changes.

**Comment by pablodip** [comment]
I don't think that we should remove `repo_name` from the database, since we are using it in the interface and want fact access to it.

To me the goal/scope of this could be to not use the repo name as identifier, that is an identifier that can change, but just the actual identifier (repo_id), which is an inmutable identifier as you said.

What do you think?

**Comment by siphiuel** [comment]
Yup, updated the solution in the description.
