### ISSUE TITLE
Add offline transaction signing support (Infura)

### ISSUE THREAD

**Issue by siphiuel** [status-im/open-bounty#302]
### User Story
Contributors often face issues setting up Geth locally. It would be nice to support Infura as a remote Ethereum node. This would simplify local setup.

### Description
Working with Infura requires offline transaction signing, as remote Infura node does not have access to local wallet file like Geth does. This means that transactions have to be signed with user's keys before they are being sent to Ethereum node.

### Solution
Implement offline transaction signing. Connection to Infura would then be configured by enabling an option in `config.edn` file and providing Infura node URL as a value of `:eth-rpc-url` option.

**Comment by pablodip** [comment]
@siphiuel This is nice, and thanks for having a look at it! :)

Before delving into the pull request, I have some concerns about the issue:

* To me the goal of the issue isn't to allow offline signing, but to allow to access to Ethereum in two ways: Geth and Infura. But just we do offline signing with Infura, but not with Geth yet (which would be ideal as well, but for another issue), but please correct me if I'm wrong.
* How should we allow to customise to use either Geth or Infura?
* Is the goal of the issue to use Infura in both dev and prod or only dev? I think that the equal we keep dev and prod, probably the better.
* How should we keep testing and QA from here on so that we ensure that things aren't broken with either type?

**Comment by siphiuel** [comment]
- Actually, there should be no reason offline signing should not work with Geth as well. Infura runs Geth or Parity nodes as I understand. Offline signing is a prerequisite to be able to connect to nodes that do not run with an unlocked account (because if they are, they do tx signing by themselves).
- I've mentioned Infura because it is a prominent example of a remote Geth node with a locked account, but it should be in no way different from the latter. So former is a subset of the latter.
- I'd say that at least in dev because it will affect first-time contributors the most. If we agree to use in prod, then it's probably even better - less hassle with Geth restarts for us
- I think that we should have an integration test that goes full cycle (unless we do already) - create an issue, label it as a bounty, post a pr with a "fix", merge, confirm payout.

**Comment by pablodip** [comment]
1.) That's nice! Even if we run our own nodes, better to use them without unlocking any accounts.
4.) Any idea to handle this? Is this somehow covered in the end-to-end tests? cc @churik

**Comment by martinklepsch** [comment]
**Regarding testing:** I think one way could be a simple shell script and some JS to control [puppeteer](https://github.com/GoogleChrome/puppeteer). I'd be happy to create a proof-of-concept of this after I finished the new landing page.

**Comment by pablodip** [comment]
4.) @martinklepsch There are already some end-to-end tests in the repo. Probably not needed to replicate that in a new kind of script.

**Comment by martinklepsch** [comment]
**RE testing** @pablodip fair enough, didn't see those.

**Comment by churik** [comment]
@martinklepsch they have documentation actually.
https://github.com/status-im/open-bounty/blob/develop/doc/testing.md, section Status Open Bounty end-to-end tests
