### ISSUE TITLE
User-owned bounties are not updated on Manage Payouts page

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#361]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: 'Manage payouts' is not updated automatically, so in order to see New Claim or that `Confirm` button is enabled - you should manually reload page
![confirm](https://user-images.githubusercontent.com/4557972/37592649-02349a92-2b78-11e8-906f-c47e2893cd13.png)

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
'Manage payouts' is updated automatically

#### Actual behavior
[comment]: # (Describe what actually happened.)
'Manage payouts' is not updated automatically

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
*Requirements*: GH account is whitelisted, signed app, test application is added to repo;
- Open issue with bounty
- Create PR with `Fixes #issue` in comment
- Merge PR
- Log in and open 'Manage payouts' 

### Additional Information
[comment]: # (Were you using an Ethereum wallet connected to your browser (MetaMask/Parity chrome plugin). Or Mist?)
* Ethereum wallet used: MetaMask

**OS:**  Mac OS High Sierra
**Browser:** Chrome 64

**Comment by martinklepsch** [comment]
So the issue here is that `commiteth.core/load-data` refreshes all open bounties but does not refresh user-specific (i.e. owned) bounties (`:owner-bounties`).


**Quick fix**: also update `:owner-bounties` in `commiteth.core/load-data`. This means basically dispatching the same events as when the user is being logged in: https://github.com/status-im/open-bounty/blob/2eb2de2888d30751773674543f918849c80794f6/src/cljs/commiteth/handlers.cljs#L229-L230

**For Bonus Points**: Currently `:owner-bounties` and other bounties are stored in different places in the re-frame app-state. This separation doesn't make much sense. In theory we should be able to differentiate between bounties a user is owning and "other" bounties easily and create subscriptions to return these groups.
