### ISSUE TITLE
Use Github APIs to sync state instead of webhooks 

### ISSUE THREAD

**Issue by rcullito** [status-im/open-bounty#426]
This is meant to generally address a certain class of issue around discrepancies between github state and the local SOB state – which is currently linked via webhooks listening for manually generated user actions taken on Github's UI. 

The goal here would be to replace the need for taking a defined series of manual steps with a central function such as `refresh-state`

examples of specific issues this should help address include:
- https://github.com/status-im/open-bounty/issues/414
- https://github.com/status-im/open-bounty/issues/416
- https://github.com/status-im/open-bounty/issues/417
- https://github.com/status-im/open-bounty/issues/423
- https://github.com/status-im/open-bounty/issues/362

**Comment by martinklepsch** [comment]
To expand on this: the issues @rcullito linked are all caused by our DB state getting out of sync with the "source of truth" (which is GitHub). Our current approach derives state from a set of webhook payloads. This is troubling for two reasons:

- Missing a single webhook will cause our database to get out of sync with no way of catching up
- We need to perfectly handle each webhook event from edits to label changes

An alternative approach to doing this kind of event sourcing on webhook payloads might be utilizing GitHub's API to derive the state that should be in our database. This could still be triggered by incoming webhooks but would allow us to elegantly avoid the two problems outlined above.

In case of trouble, we could also easily initiate this process from the REPL or via an API.

**Comment by siphiuel** [comment]
Some time ago when we had to re-check our data against Github state we used a small fn: https://github.com/status-im/open-bounty/blob/a70696f26b24d9335efed679264d338eecae5ae2/src/clj/commiteth/github/core.clj#L367. It uses GitHub API search.Hopefully we can use it for the purposes of copying the GitHub state, for issues at least. Need to recall better how to find PRs, because we don't put a label on PRs, so maybe there's another way.

**Comment by martinklepsch** [comment]
I think the `(refresh-state issue-id)` function would take the `issue-id` as an argument, PR links could then be extracted from text or references not sure what GitHub's API provides for that. 
Everytime we get a webhook that references an issue (could be issue or PR events) we call `refresh-state` for that issue. Or so 🙂

**Comment by martinklepsch** [comment]
I reached out to GitHub support to understand how we could use their API to identify PRs that are claims towards a bounty/issue. While it's not directly possible to retrieve the PR that *closed* an issue the (beta) timeline API allows finding all PRs that referenced an issue. Parsing the body and title as we do now should then allow us to identify claims quite easily:

```
curl -H 'Accept: application/vnd.github.mockingbird-preview' \
  https://api.github.com/repos/TestingEnvENV/TestEnvAtt5/issues/186/timeline
```
