### ISSUE TITLE
Ability to tweet bounties automatically.

### ISSUE THREAD

**Issue by Smokyish** [status-im/open-bounty#52]
### User Story

As a user/developer, I want to have my bounties broadcasted to Twitter so more people will know about it.

### Description

*Type*: Feature

*Summary*: When a new bounty gets added to CommitETH, a bot will broadcast that bounty to Twitter. This can be used via the CommitETH Twitter account or a fresh one made for this purpose. 

Also consider:
- Tweeting made optional, user needs to enable the function via CommitETH page.
- Add the ability for a user/developer to add hashtags to engage a more specific and/or broad audience on Twitter.

**Comment by tpatja** [comment]
A couple questions:

1. Would the tweets include only "new bounty" events? If so, we cannot have a balance in the tweet, since no ETH has been added to the contract yet.

2. What would optional tweeting look like? I guess a checkbox in the manage repositories view, visible for enabled repos. If we add this, the bounty events are still shown on the public activity feed and public bounties list, so maybe a more general "keep my bounties private" setting could be considered instead?

One simple way for tweets to work would be to tweet everything the activity feed contains (new-bounty, bounty-balance-updated, bounty-claim and bounty-payout events) as the events happen.

**Comment by Smokyish** [comment]
1. I think that it should be handled when the event is complete, so it has all the data, repo and issue name, balance, the QR image could be attached if you want. Ideally the first three would always be included, user/repo name, issue title and balance.
2. Well a general 'private bounties' setting is another issue, i think it might be useful for some teams where one wants to pay the team per contributions, but not allow outsiders for development bounties, then again, doesn't this kind of go against the community driven development model and paying people for contributing to open source projects?
A setting to just enable/disable the tweet function should suffice, maybe even add a manual tweeting option to only tweet out those that the user manually wants to broadcast (probably requires a limit of 1 tweet/issue or a lockdown period to prevent spamming).

I'm not sure how to handle changing balances, as that might also cause quite a lot of spam if it updates frequently.

**Comment by noman-land** [comment]
I've been working with @pablanopete on a prototype of an auto-posting Twitter bot. You can check the repo here: https://github.com/noman-land/status-open-bounty-bot

Right now it just polls the public SOB endpoints and looks for new bounties and new activities.

Regarding the discussions above. The SOB endpoint for bounties has no concept of "new" vs "updated" bounties. If a bounty is updated, its updated time is updated and its ordering in the endpoint result is modified. This triggers an update of the Twitter bot. 

Our solution is to simply not tweet about $0 bounties, and as a result, only tweet upon updated bounties. 

This does not address any sort of user options about whether or not to tweet, it simply listens to what the website shows and tweets about it.

This related so https://github.com/status-im/open-bounty/issues/38 as well.
